name: Deploy para GitHub Pages

on:
  push:
    branches: [ main ]

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Instalar dependências
        run: npm install

      - name: Buildar (injetando as chaves)
        env:
          VITE_API_TOKEN: ${{ secrets.VITE_API_TOKEN }}
        run: npm run build

      - name: Publica no Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist